insert into shelters(name,
                     type,
                     address,
                     schedule,
                     scheme,
                     safety,
                     docs,
                     rules,
                     arrangements,
                     arrangements_for_puppy,
                     arrangements_for_cripple,
                     movement,
                     expert_advices_first,
                     expert_advices_next,
                     reject_reasons)
values ('Приют для собак',
        'DOGS',
        'Адрес...',
        'Режим работы...',
        'Схема проезда...',
        'Будьте осторожны...',
        'Документы...',
        'Правила...',
        'Рекомендации...',
        'Рекомендации...',
        'Рекомендации...',
        'Рекомендации...',
        'Советы кинолога...',
        'Советы кинолога...',
        'Причины отклонения...');

insert into shelters(name,
                     type,
                     address,
                     schedule,
                     scheme,
                     safety,
                     docs,
                     rules,
                     arrangements,
                     arrangements_for_puppy,
                     arrangements_for_cripple,
                     movement,
                     expert_advices_first,
                     expert_advices_next,
                     reject_reasons)
values ('Приют для кошек',
        'CATS',
        'Адрес...',
        'Режим работы...',
        'Схема проезда...',
        'Будьте осторожны...',
        'Документы...',
        'Правила...',
        'Рекомендации...',
        'Рекомендации...',
        'Рекомендации...',
        'Рекомендации...',
        'Советы эксперта...',
        'Советы эксперта...',
        'Причины отклонения...');